package com.ai.itops.security.permission;

/** Workspace RBAC 操作权限。 */
public enum WorkspacePermission {
    WORKSPACE_READ,
    WORKSPACE_UPDATE,
    WORKSPACE_DELETE,
    OWNERSHIP_TRANSFER,
    MEMBER_READ,
    MEMBER_INVITE,
    MEMBER_REMOVE,
    MEMBER_ROLE_UPDATE,
    KNOWLEDGE_BASE_READ,
    KNOWLEDGE_BASE_CREATE,
    KNOWLEDGE_BASE_UPDATE,
    KNOWLEDGE_BASE_DELETE,
    DOCUMENT_READ,
    DOCUMENT_UPLOAD,
    DOCUMENT_UPDATE,
    DOCUMENT_DELETE,
    DIAGNOSIS_EXECUTE
}
